### ISSUE TITLE
Checking in for Milestone #3

### ISSUE THREAD

**Issue by pengzedong** [jacksonhack/SP23-Team6#15]
Hello @jacksonhack and all,

Just checking to see how the actual implementations go. Please provide some updates in terms of the Milestone #3 progress. Keep in mind that your team's Google Colab project needs to add us ([nan.nn.niu@gmail.com] for the instructor and [pengzedong@gmail.com] for the TA), so that we can run your code as part of the grading. Let us know if you have any questions.

Thanks,
Zedong and @nanniu

**Comment by nanniu** [comment]
Thanks for the update @jacksonhack Let us know if you have any questions, as we're closing in to the deadline of Milestone #3 (2/24/2023).
