### ISSUE TITLE
Accuracy Testing and Tuning

### ISSUE THREAD

**Issue by jacksonhack** [jacksonhack/SP23-Team6#16]
Do accuracy testing on our model, and use it to tune the cutoff for "old" vs "new". Essentially take out 10% of the "old" features and 10% of the new features and use them to test the accuracy of our model's classification (10% is an example number, it doesn't necessarily have to be this). Do this for a handful of different month cutoffs for the Zoom data and find what gives the most accuracy (i.e., first 5 months/last 7 months vs first 6 months/last 6 months vs first 7 months/last 5 months), and come to a conclusion on what worked best (what cutoff leads to best accuracy of model).

Record and report results for Milestone 4 presentation.

**Comment by jacksonhack** [comment]
@nanniu this is the first task of our Sprint 2, per our meeting earlier

**Comment by nanniu** [comment]
Good job @jacksonhack What's of essence here is to check classification accuracy, and incorporate such accuracy into answering 'old / older' versus 'new / newer'.
