### ISSUE TITLE
Apply our Model to WebEx data

### ISSUE THREAD

**Issue by jacksonhack** [jacksonhack/SP23-Team6#17]
- Clean and import webex data

- [ ] Webex Data is ran through all functions
- [ ] Webex data is available for all

**Comment by jacksonhack** [comment]
@nanniu this is the second task of our Sprint 2, per our meeting earlier

**Comment by nanniu** [comment]
Very good notes about this one @jacksonhack ! I have nothing to add :-)

**Comment by jacksonhack** [comment]
finished
